### ISSUE TITLE
initOptions

### ISSUE THREAD

**Issue by cnishina** [cnishina/webdriver-manager-replacement#59]
Instead of doing this:

```
    // if value is not set, nothing from wdm gets logged.
    log.setLevel('info');

    // Should create an initOptions method instead of this...
    chrome = new wdm.ChromeDriver({});
    selenium = new wdm.SeleniumServer({});
    const options = {
      providers: [{
        binary: chrome
      }],
      server: {
        binary: selenium,
        runAsNode: true,
        runAsDetach: true
      }
    };
    return wdm.update(options).then(() => {
      return wdm.start(options);
    });
```

Create a initOptions method to create options.

**Comment by igniteram** [comment]
Once this is done, I will start replacing webdriver-manager with webdriver-manager-replacement in my projects ;)

**Comment by igniteram** [comment]
It works with webdriverIO have you tried using it with protractor ? I tried to use this with protractor,  it is looking for default`update-config.json` and forcing to run `webdriver-manager update`. I have created a repository for it - [wdm-protractor](https://github.com/igniteram/wdm-protractor).

**Comment by cnishina** [comment]
I decided to that each provider would have it's own config.  So if you download chromedriver, the file `chromedriver.config.json` is written and we don't have to wait for all the other downloads to complete. If one of the downloads failed in the old way, I believe `update-config.json` is not written. Because there is not `update-config.json`, the following will not work right now: local driver and direct connect.

We will roll this out with a angular/webdriver-manager 13.0.0-beta and patch the driver providers in the next major version of Protractor. Maybe a Protractor 6.0.0-beta so we can test out the entire workflow.

**Comment by cnishina** [comment]
Okay, I looked at the config. You are missing the following `seleniumAddress: "http://127.0.0.1:4444/wd/hub"`. If you miss this, the test will try to launch locally. Huzzah!
